name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image For Web App
      run: docker build . --file ./src/Web/cube/Dockerfile --tag yuanzhitang/cubewebapp:latest
    - name: Build Docker image For Board Service
      run: docker build . --file ./src/Services/Board/Board.API/Dockerfile --tag yuanzhitang/cubeboardservice:latest
    - name: Build Docker image For User Service
      run: docker build . --file ./src/Services/User/User.API/Dockerfile --tag yuanzhitang/cubeuserservice:latest
    - name: Build Docker image For Identity Service
      run: docker build . --file ./src/Services/Identity/Identity.API/Dockerfile --tag yuanzhitang/cubeidentityservice:latest
    - name: Login to registry
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }} docker.io
    - name: Push Image for Web App
      run: docker push yuanzhitang/cubewebapp:latest
    - name: Push Image for Board Service
      run: docker push yuanzhitang/cubeboardservice:latest
    - name: Push Image for User Service
      run: docker push yuanzhitang/cubeuserservice:latest
    - name: Push Image for Identity Service
      run: docker push yuanzhitang/cubeidentityservice:latest

      
